#!/usr/bin/env bash
#
# Shared helpers for scripts/dev.sh and scripts/setup.sh.
# Sourced, never executed directly.
#

ULINK_DEV_DIR="${ULINK_DEV_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.dev}"
ULINK_MARIADB_DIR="$ULINK_DEV_DIR/mariadb"
ULINK_MARIADB_DATA="$ULINK_DEV_DIR/data"
ULINK_MARIADB_RUN="$ULINK_DEV_DIR/run"
ULINK_PHP_EXT_DIR="$ULINK_DEV_DIR/php-ext"
ULINK_MARIADB_LIB="$ULINK_MARIADB_DIR/usr/lib/x86_64-linux-gnu"

ulink_ensure_dirs() {
    mkdir -p "$ULINK_MARIADB_RUN" "$ULINK_PHP_EXT_DIR/active" "$ULINK_DEV_DIR/logs"

    # config/config.php reads <project root>/.env, so that is where it goes.
    local env_file="$PROJECT_ROOT/.env"

    if [ ! -f "$env_file" ]; then
        cat > "$env_file" <<EOF
# Generated by scripts/dev.sh -- local development defaults.
# Delete this file to fall back to the built-in defaults.
ULINK_DB_HOST=127.0.0.1
ULINK_DB_PORT=${ULINK_DB_PORT:-3307}
ULINK_DB_NAME=ulink_db
ULINK_DB_USER=root
ULINK_DB_PASS=
ULINK_DEBUG=1
ULINK_ALLOWED_ORIGINS=*
ULINK_HSTS=0
EOF
        echo "Created $env_file"
    fi
}

# The bundled MariaDB is unpacked from the distribution .deb files so no root
# access is needed. Returns 0 when a server is available.
ulink_ensure_database() {
    if [ -x "$ULINK_MARIADB_DIR/usr/sbin/mariadbd" ]; then
        return 0
    fi

    if ! command -v apt-get > /dev/null 2>&1; then
        echo "error: no bundled MariaDB and apt-get is unavailable." >&2
        return 1
    fi

    echo "Unpacking MariaDB into .dev/mariadb (one time, no root required)..."
    mkdir -p "$ULINK_MARIADB_DIR"

    local packages=(
        mariadb-server
        mariadb-server-core
        mariadb-client
        mariadb-client-core
        mariadb-common
        libmariadb3
        libconfig-inifiles-perl
        libaio1t64
        libmecab2
    )

    local tmp
    tmp="$(mktemp -d)"
    ( cd "$tmp" && apt-get download "${packages[@]}" > /dev/null 2>&1 ) || {
        echo "error: could not download MariaDB packages." >&2
        rm -rf "$tmp"
        return 1
    }

    local deb
    for deb in "$tmp"/*.deb; do
        dpkg-deb -x "$deb" "$ULINK_MARIADB_DIR"
    done
    rm -rf "$tmp"

    [ -x "$ULINK_MARIADB_DIR/usr/sbin/mariadbd" ]
}

# Extensions the app genuinely needs, and the distribution packages that
# provide them. The CLI PHP ships without pdo_mysql, and mbstring is needed for
# the UTF-8 aware validators in config/bootstrap.php.
#
# Load order matters: mysqlnd must be initialised before pdo_mysql.
ULINK_PHP_REQUIRED_EXT="pdo_mysql mbstring"
ULINK_PHP_PACKAGES="php-mysql php8.5-mbstring"
ULINK_PHP_EXT_FILES="mysqlnd.so pdo_mysql.so mbstring.so"

# Echo 0 when every required extension is already built into the running PHP.
ulink_php_ext_native() {
    local loaded ext
    loaded="$(php -m 2>/dev/null)"
    for ext in $ULINK_PHP_REQUIRED_EXT; do
        echo "$loaded" | grep -qx "$ext" || return 1
    done
    return 0
}

# Unpack the extension .debs into .dev/php-ext so no root access is needed.
ulink_ensure_php_extensions() {
    ulink_php_ext_native && return 0

    if [ ! -f "$ULINK_PHP_EXT_DIR/active/mbstring.so" ] \
       || [ ! -f "$ULINK_PHP_EXT_DIR/active/pdo_mysql.so" ]; then
        echo "Unpacking the required PHP extensions into .dev/php-ext..."
        local tmp
        tmp="$(mktemp -d)"
        # shellcheck disable=SC2086
        if ! ( cd "$tmp" && apt-get download $ULINK_PHP_PACKAGES > /dev/null 2>&1 ); then
            echo "warning: could not download the PHP extension packages." >&2
            echo "  Install them with: sudo apt-get install php-mysql php8.5-mbstring" >&2
            rm -rf "$tmp"
            return 1
        fi

        local deb
        for deb in "$tmp"/*.deb; do
            dpkg-deb -x "$deb" "$ULINK_PHP_EXT_DIR"
        done
        rm -rf "$tmp"

        mkdir -p "$ULINK_PHP_EXT_DIR/active"
        find "$ULINK_PHP_EXT_DIR" -name '*.so' -exec cp {} "$ULINK_PHP_EXT_DIR/active/" \; 2>/dev/null || true
    fi

    return 0
}

# Echo the -d extension flags needed to make `php` see the bundled extensions.
ulink_php_flags() {
    ulink_php_ext_native && return 0

    local flags="" so
    for so in $ULINK_PHP_EXT_FILES; do
        if [ -f "$ULINK_PHP_EXT_DIR/active/$so" ]; then
            flags="$flags -d extension=$ULINK_PHP_EXT_DIR/active/$so"
        fi
    done
    echo "$flags"
}

ulink_php_run() {
    # shellcheck disable=SC2046
    php $(ulink_php_flags) "$@"
}

ulink_process_alive() {
    local pidfile="$1"
    [ -f "$pidfile" ] || return 1
    local pid
    pid="$(cat "$pidfile" 2>/dev/null || true)"
    [ -n "$pid" ] || return 1
    kill -0 "$pid" 2>/dev/null
}

ulink_start_database() {
    local pidfile="$ULINK_MARIADB_RUN/mysqld.pid"

    if ulink_process_alive "$pidfile"; then
        return 0
    fi

    if ! ulink_ensure_database; then
        echo "error: no database server available." >&2
        return 1
    fi

    if [ ! -d "$ULINK_MARIADB_DATA/mysql" ]; then
        echo "Initialising the database files..."
        rm -rf "$ULINK_MARIADB_DATA"
        mkdir -p "$ULINK_MARIADB_DATA"
        LD_LIBRARY_PATH="$ULINK_MARIADB_LIB" \
        PATH="$ULINK_MARIADB_DIR/usr/bin:$PATH" \
            "$ULINK_MARIADB_DIR/usr/bin/mariadb-install-db" \
                --user="$(id -un)" \
                --basedir="$ULINK_MARIADB_DIR/usr" \
                --datadir="$ULINK_MARIADB_DATA" \
                --auth-root-authentication-method=normal \
                --skip-test-db > "$ULINK_DEV_DIR/logs/mariadb-install.log" 2>&1 \
            || { echo "error: mariadb-install-db failed, see .dev/logs/mariadb-install.log" >&2; return 1; }
    fi

    echo "Starting MariaDB on port ${ULINK_DB_PORT:-3307}..."
    LD_LIBRARY_PATH="$ULINK_MARIADB_LIB" \
    setsid nohup "$ULINK_MARIADB_DIR/usr/sbin/mariadbd" \
        --no-defaults \
        --user="$(id -un)" \
        --basedir="$ULINK_MARIADB_DIR/usr" \
        --datadir="$ULINK_MARIADB_DATA" \
        --socket="$ULINK_MARIADB_RUN/mysqld.sock" \
        --port="${ULINK_DB_PORT:-3307}" \
        --bind-address=127.0.0.1 \
        --pid-file="$pidfile" \
        --skip-name-resolve \
        --log-error="$ULINK_DEV_DIR/logs/mariadb.log" \
        < /dev/null > "$ULINK_DEV_DIR/logs/mariadb-stdout.log" 2>&1 &

    # Wait for the socket to answer.
    local i
    for i in $(seq 1 40); do
        if LD_LIBRARY_PATH="$ULINK_MARIADB_LIB" \
           "$ULINK_MARIADB_DIR/usr/bin/mariadb" \
               --socket="$ULINK_MARIADB_RUN/mysqld.sock" -u root -e "SELECT 1" > /dev/null 2>&1; then
            echo "Database is up."
            return 0
        fi
        sleep 0.5
    done

    echo "error: the database did not start, see .dev/logs/mariadb.log" >&2
    return 1
}

ulink_start_web() {
    local pidfile="$ULINK_DEV_DIR/web.pid"

    if ulink_process_alive "$pidfile"; then
        return 0
    fi

    mkdir -p "$PROJECT_ROOT/logs"

    echo "Starting the web server on ${ULINK_HTTP_HOST:-127.0.0.1}:${ULINK_HTTP_PORT:-8080}..."
    (
        cd "$PROJECT_ROOT"
        # shellcheck disable=SC2046
        setsid nohup php $(ulink_php_flags) -S "${ULINK_HTTP_HOST:-127.0.0.1}:${ULINK_HTTP_PORT:-8080}" \
            -t "$PROJECT_ROOT" \
            "$PROJECT_ROOT/router.php" \
            < /dev/null > "$PROJECT_ROOT/logs/web.log" 2>&1 &
        echo $! > "$pidfile"
    )
}

ulink_stop_process() {
    local pidfile="$1" label="$2"

    if ulink_process_alive "$pidfile"; then
        local pid
        pid="$(cat "$pidfile")"
        # Kill the whole process group: the dev server forks workers.
        kill -TERM -- "-$pid" 2>/dev/null || kill -TERM "$pid" 2>/dev/null || true
        sleep 1
        kill -KILL -- "-$pid" 2>/dev/null || true
        echo "Stopped $label."
    fi
    rm -f "$pidfile"
}

# ---------------------------------------------------------------- sql access
#
# Both test suites need to read and write rows directly: there is no API that
# creates an empty community, flips `is_private`, or deletes a post, and those
# are exactly the states the access-control tests are about. Sourced rather than
# duplicated so both suites talk to the same database the same way.

# db SQL -> tab-separated rows on stdout, nothing on failure.
ulink_db() {
    LD_LIBRARY_PATH="$ULINK_MARIADB_LIB" \
        "$ULINK_MARIADB_DIR/usr/bin/mariadb" \
        --socket="$ULINK_MARIADB_RUN/mysqld.sock" \
        -u "${ULINK_DB_USER:-root}" "${ULINK_DB_NAME:-ulink_db}" -N -B -e "$1" 2>/dev/null
}

# db_ro SQL -> the same output as ulink_db(), but a statement that fails is
# reported and does not come back looking like an empty result.
#
# Use this to *read a value the script will later splice back into a restore*.
# There, "no rows" and "the query did not run" are not the same thing, and
# ulink_db() cannot tell them apart because it discards stderr. A snapshot taken
# from a column that does not exist therefore returned an empty string, the
# `[ -n "$SNAPSHOT" ]` guard treated that as "nothing to restore", and the
# restore quietly never happened. That is not hypothetical: this suite
# snapshotted community_members.created_at - the column is joined_at - and the
# seeded admin of community 1 stayed demoted to a plain member after every run
# while the suite reported success.
ulink_db_ro() {
    local out status
    out=$(LD_LIBRARY_PATH="$ULINK_MARIADB_LIB" \
        "$ULINK_MARIADB_DIR/usr/bin/mariadb" \
        --socket="$ULINK_MARIADB_RUN/mysqld.sock" \
        -u "${ULINK_DB_USER:-root}" "${ULINK_DB_NAME:-ulink_db}" -N -B -e "$1" 2>&1)
    status=$?

    if [ "$status" -ne 0 ]; then
        printf 'ulink_db_ro: statement failed (%d): %s\n' "$status" "$out" >&2
        return "$status"
    fi

    printf '%s' "$out"
}

# Remove everything the two test suites created, and nothing else.
#
# The suites create posts, comments, likes, messages and attachments that no
# endpoint can take back - there is no delete-post endpoint - so they pile up a
# handful of rows per run. After twenty runs the demo database held 59 posts for
# a single user against a seed of 18, and a suite assertion comparing the
# profile header's post count with the posts listed below it started failing for
# a reason that had nothing to do with the code under test. The suites now sweep
# after themselves.
#
# Every marker below is something only these scripts produce:
#
#   * the seed uploads no attachments at all, so `attachment_path IS NOT NULL`
#     identifies a test message exactly;
#   * the seed's post and comment text never contains any of these literals;
#   * stored attachment filenames are 32 random hex characters plus an extension
#     (see ulink_save_attachment), and the seed writes no files there.
#
#   * the throwaway accounts the register section creates are `tester_<epoch>@`
#     and `pic_<epoch>@example.com`, and no seed address is on example.com.
#
# Pass the moment the run started, as `date -u '+%Y-%m-%d %H:%M:%S'`, to bound
# the sweep of `login_attempts`. That one table records no user agent, so the
# only handle on it is a timestamp - and the login limiter counts *failed*
# attempts, so leaving them behind would eventually lock a demo account out.
# The other two log tables are matched on their User-Agent instead, because a
# time window there would also catch the developer's own browser session.
#
# Does nothing if the database is not reachable, which is the normal case for
# ULINK_BASE_URL pointed at another host.
ulink_sweep_test_data() {
    local root="${PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
    local since="${1:-}"
    local q

    if [ "$(ulink_db 'SELECT 1')" != "1" ]; then
        return 0
    fi

    # Children before parents. notifications reference posts and comments
    # polymorphically through reference_id, so they go first.
    for q in \
        "DELETE FROM notifications
            WHERE reference_id IN (SELECT id FROM posts WHERE content LIKE '%API suite%')
               OR reference_id IN (SELECT id FROM comments WHERE content IN
                     ('Automated comment.',
                      'Comment to raise an unread notification.',
                      'A second unread one.'))
               OR content LIKE '%API suite%'
               OR content LIKE '%\"Automated comment.\"%'
               OR content LIKE '%Comment to raise an unread notification%'
               OR content LIKE '%A second unread one%'" \
        "DELETE FROM post_likes
            WHERE post_id IN (SELECT id FROM posts WHERE content LIKE '%API suite%')" \
        "DELETE FROM comments
            WHERE content IN ('Automated comment.',
                              'Comment to raise an unread notification.',
                              'A second unread one.')
               OR post_id IN (SELECT id FROM posts WHERE content LIKE '%API suite%')" \
        "DELETE FROM messages
            WHERE attachment_path IS NOT NULL
               OR message IN ('Hello from the API suite.',
                              'Sent with the alias key.',
                              'here are my notes')
               OR message LIKE '%API suite%'" \
        "DELETE FROM posts WHERE content LIKE '%API suite%'" \
    ; do
        ulink_db "$q"
    done

    # The accounts the register section creates, and the avatars one of them
    # uploads. Both addresses are on example.com, which no seed uses, so this
    # cannot reach demo data.
    local thrown_away
    thrown_away=$(ulink_db "SELECT GROUP_CONCAT(id) FROM users WHERE email LIKE '%@example.com'")
    if [ -n "${thrown_away:-}" ]; then
        ulink_db "DELETE FROM user_sessions WHERE user_id IN (${thrown_away})"
        ulink_db "DELETE FROM user_activities WHERE user_id IN (${thrown_away})"
        ulink_db "DELETE FROM notifications
                    WHERE user_id IN (${thrown_away}) OR from_user_id IN (${thrown_away})"
        ulink_db "DELETE FROM friendships
                    WHERE user_id_1 IN (${thrown_away}) OR user_id_2 IN (${thrown_away})"
        ulink_db "DELETE FROM post_likes WHERE user_id IN (${thrown_away})"
        ulink_db "DELETE FROM comments WHERE user_id IN (${thrown_away})"
        ulink_db "DELETE FROM posts WHERE user_id IN (${thrown_away})"
        ulink_db "DELETE FROM messages
                    WHERE sender_id IN (${thrown_away}) OR receiver_id IN (${thrown_away})"
        ulink_db "DELETE FROM users WHERE id IN (${thrown_away})"
    fi

    # Log rows. Both user_sessions and user_activities record the User-Agent, and
    # curl sends "curl/<version>" unless told otherwise - which is what every
    # request from these scripts is. Matching on that is exact: the first version
    # of this swept them by timestamp instead, and the side effect was that
    # running the tests logged you out of the app in your own browser, because
    # your session row had been created within the same window.
    ulink_db "DELETE FROM user_sessions  WHERE user_agent LIKE 'curl/%'"
    ulink_db "DELETE FROM user_activities WHERE user_agent LIKE 'curl/%'"

    # login_attempts records no user agent, so it is the one table that has to be
    # cut by time. Two minutes of slack, so a run that begins on a second boundary
    # still catches the failures it made at the start.
    #
    # Removing the *failed* rows is not merely tidiness: the login limiter counts
    # them, and the suite deliberately fails logins, so leaving them would
    # eventually lock a demo account out. The successful ones are only audit
    # noise. Both are dropped, which means a developer signed in at the same time
    # loses that one record - no state, no session, nothing they can observe.
    if [ -n "$since" ]; then
        local cut
        cut=$(date -u -d "$since -2 minutes" '+%Y-%m-%d %H:%M:%S' 2>/dev/null) || cut="$since"
        ulink_db "DELETE FROM login_attempts WHERE created_at >= '$cut'"
    fi

    # Uploaded files, after their rows are gone. Matched by name so this also
    # catches a file whose row an earlier partial run already removed - which is
    # how nine orphans accumulated in uploads/messages.
    #
    # The second pattern matters as much as the first. Every stored upload is
    # accompanied by `<image>.htaccess`, which does *not* match the image
    # pattern - its name ends in `.htaccess`, not in an extension - so sweeping
    # only the images left a guard behind for each one. Over a few hundred runs
    # that is a directory of a few hundred files that guard nothing, and the
    # count grows without bound because the file each guard belongs to is gone.
    local dir
    for dir in messages profiles; do
        if [ -d "$root/uploads/$dir" ]; then
            find "$root/uploads/$dir" -maxdepth 1 -type f -regextype posix-extended \
                -regex ".*/[0-9a-f]{32}\.[A-Za-z0-9]+(\.htaccess)?" -delete 2>/dev/null || true
        fi
    done

    return 0
}

# sqlval VALUE -> a SQL literal for a value read back out of the database.
#
# The suites snapshot a row, then splice it into a restore statement. A datetime
# cannot go in bare: `responded_at = 2026-10-02 18:44:48` is a syntax error, and
# since ulink_db() discards stderr the restore failed silently - leaving the
# friendship deleted, which is exactly the damage the restore existed to undo.
# NULL has to stay bare for the opposite reason: `'NULL'` is a string, and the
# column is an integer or a timestamp.
sqlval() {
    case "${1:-}" in
        ''|NULL) printf 'NULL' ;;
        *[!0-9]*) printf "'%s'" "${1//\'/\'\'}" ;;
        *)       printf '%s' "$1" ;;
    esac
}
